<?php

namespace App\Controller\Admin;

use App\Entity\Cars;
use App\Form\CarsType;
use App\Repository\CarsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\File;

/**
 * @Route("/admin/cars")
 */
class CarsController extends AbstractController
{
    /**
     * @Route("/", name="admin_cars_index", methods={"GET"})
     */
    public function index(CarsRepository $carsRepository): Response
    {
        $car=$carsRepository->getAllCars();
        return $this->render('admin/cars/index.html.twig', [
            'cars' => $car,
        ]);
    }

    /**
     * @Route("/new", name="admin_cars_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $cars = new Cars();
        $form = $this->createForm(CarsType::class, $cars);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //*****************file upload******************>>>>>>>>>>>>

            /**@var file $file */
            $file = $form['image']->getData();
            if($file){
                $fileName = $this->generateUniqueFileName() . '.' .$file->guessExtension();  // uniq id ile kaydediyor yüklenen resimleri dosya yolu ile beraber alıyor
                //Move the file to the directory where brochures are stored
                try{
                    $file->move(
                        $this->getParameter('images_directory'), //Servis.yaml de tanımladığımız resim yolu
                        $fileName
                    );
                } catch (FileException $e){
                    //... handle exception if something happens during file upload
                }
                $cars->setImage($fileName);  //Related upload file name with cars table image field
            }
            //*****************file upload******************>>>>>>>>>>>>
            $user = $this->getUser();
            $cars->setUserid($user->getId());

            $entityManager->persist($cars);
            $entityManager->flush();

            return $this->redirectToRoute('admin_cars_index');
        }

        return $this->render('admin/cars/new.html.twig', [
            'cars' => $cars,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_cars_show", methods={"GET"})
     */
    public function show(Cars $cars): Response
    {
        return $this->render('admin/cars/show.html.twig', [
            'car' => $cars,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_cars_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Cars $cars): Response
    {
        $form = $this->createForm(CarsType::class, $cars);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /**@var file $file */
            $file = $form['image']->getData();
            if($file){
                $fileName = $this->generateUniqueFileName() . '.' .$file->guessExtension();
                //Move the file to the directory where brochures are stored
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e){
                    //... handle exception if something happens during file upload
                }
                $cars->setImage($fileName);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_cars_index');
        }

        return $this->render('admin/cars/edit.html.twig', [
            'cars' => $cars,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */

    private function generateUniqueFileName()
    {
        //md5() reduces the similarity of the file names generated by
        //uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="admin_cars_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Cars $cars): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cars->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($cars);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_cars_index');
    }

}
